# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 'fluxject npm package'

on:
  push:
    tags: ['devBuild-*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm publish --tag ${GITHUB_REF##*/} --access public
      - run: npm dist-tag add dev-latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}