# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 'Fluxject Publish devBuild Package'

on:
  push:
    tags: ['*.*.*-rc-*']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org/'
    - name: Clean Install
      run: npm ci
    - name: Set new version
      run: npm version --git-tag-version false ${{ github.ref_name }}
    - name: Publish new version
      run: npm publish --provenance --tag rc
      env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}